"""PDF protocol generation"""
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
from reportlab.lib.units import inch
from datetime import datetime
import io

def generate_protocol_pdf(compound_name, stock_mM, top_dose_uM, dilution_factor=3, num_points=8):
    """Generate PDF dilution protocol"""
    
    # Create PDF in memory
    pdf_buffer = io.BytesIO()
    doc = SimpleDocTemplate(pdf_buffer, pagesize=letter)
    story = []
    styles = getSampleStyleSheet()
    
    # Title
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#1f77b4'),
        spaceAfter=12,
        alignment=1
    )
    
    story.append(Paragraph("ProtocolForge 🧬", title_style))
    story.append(Paragraph(f"Dilution Protocol: {compound_name}", styles['Heading2']))
    story.append(Spacer(1, 0.2*inch))
    
    # Metadata
    story.append(Paragraph(f"<b>Generated:</b> {datetime.now().strftime('%Y-%m-%d %H:%M')}", styles['Normal']))
    story.append(Paragraph(f"<b>Stock Concentration:</b> {stock_mM} mM", styles['Normal']))
    story.append(Paragraph(f"<b>Top Dose:</b> {top_dose_uM} µM", styles['Normal']))
    story.append(Paragraph(f"<b>Dilution Factor:</b> {dilution_factor}-fold", styles['Normal']))
    story.append(Spacer(1, 0.3*inch))
    
    # Calculate dilution series
    doses = []
    for i in range(num_points):
        dose = top_dose_uM / (dilution_factor ** i)
        doses.append(dose)
    doses = sorted(doses, reverse=True)
    
    # Dilution table
    story.append(Paragraph("Dilution Series:", styles['Heading3']))
    
    table_data = [['Tube', 'Dose (µM)', 'Volume (µL)', 'Dilution']]
    for idx, dose in enumerate(doses, 1):
        final_vol = 450
        compound_vol = (dose * final_vol) / (stock_mM * 1000)
        dilution = f"{dilution_factor}^{idx-1}" if idx > 1 else "Stock"
        
        table_data.append([
            f"{idx}",
            f"{dose:.2e}",
            f"{compound_vol:.1f}",
            dilution
        ])
    
    table = Table(table_data, colWidths=[1*inch, 1.5*inch, 1.5*inch, 1.5*inch])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1f77b4')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    
    story.append(table)
    story.append(Spacer(1, 0.3*inch))
    
    # Footer
    story.append(Paragraph(
        "<i>Generated by ProtocolForge - Automated Dilution Protocol Generator</i>",
        styles['Normal']
    ))
    
    # Build PDF
    doc.build(story)
    pdf_buffer.seek(0)
    return pdf_buffer

def generate_batch_protocol_pdf(compounds_list):
    """Generate batch PDF with all compounds"""
    
    pdf_buffer = io.BytesIO()
    doc = SimpleDocTemplate(pdf_buffer, pagesize=letter)
    story = []
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#1f77b4'),
        spaceAfter=12,
        alignment=1
    )
    
    story.append(Paragraph("ProtocolForge 🧬", title_style))
    story.append(Paragraph("Batch Dilution Protocols", styles['Heading2']))
    story.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", styles['Normal']))
    story.append(Spacer(1, 0.3*inch))
    
    # Summary table
    summary_data = [['Compound', 'Stock (mM)', 'Top Dose (µM)', 'Notes']]
    for compound in compounds_list:
        summary_data.append([
            compound.get('name', 'Unknown'),
            str(compound.get('stock_mM', 50)),
            str(compound.get('top_dose_uM', 100)),
            compound.get('notes', '')
        ])
    
    summary_table = Table(summary_data)
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1f77b4')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    
    story.append(summary_table)
    story.append(Spacer(1, 0.3*inch))
    story.append(Paragraph(
        "<i>Each compound requires individual preparation following the dilution series.</i>",
        styles['Normal']
    ))
    
    doc.build(story)
    pdf_buffer.seek(0)
    return pdf_buffer
